name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      - name: Go to app folder
        run: cd app && ls -la

      - name: Generate Gradle Wrapper (if missing)
        run: |
          cd app
          if [ ! -f gradlew ]; then
            gradle wrapper --gradle-version 8.7
          fi

      - name: Make Gradle Wrapper executable
        run: cd app && chmod +x gradlew

      - name: Build Debug APK
        run: cd app && ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
