name: Build APK from ZIP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Unzip Project
      run: |
        unzip GameTimeLimiter_final.zip -d GameTimeLimiter

    - name: Make Gradle Wrapper Executable
      run: chmod +x GameTimeLimiter/gradlew

    - name: Build Debug APK
      run: ./GameTimeLimiter/gradlew assembleDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GameTimeLimiter-APK
        path: GameTimeLimiter/app/build/outputs/apk/debug/app-debug.apk
        
